#!/usr/bin/env sh

# m1 mac specific scripting additions
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# labelling spaces
yabai -m space 1 --label gb32
yabai -m space 2 --label gb27
yabai -m space 3 --label abel

# disable tiling for specific apps

yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=on
yabai -m rule --add app="^Logi Options$" sticky=on layer=above manage=off
yabai -m rule --add app="^BetterTouchTool$" manage=off
yabai -m rule --add app="^Android File Transfer$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^FaceTime$" sticky=on layer=above manage=off
yabai -m rule --add app="^Folx" sticky=off manage=off
yabai -m rule --add app="^Colibri" sticky=off manage=off
yabai -m rule --add app="^IINA" sticky=off manage=off
yabai -m rule --add app="^Keyboard Maestro" sticky=off manage=off

# focus on any other window after closing window
yabai -m signal --add event=window_destroyed action="bash /Users/aayushbajaj/.config/yabai/scripts/window-focus-on-destroy.sh"

# limelight
# border off. using limelight bc of m1 mac.
killall limelight &>/dev/null
limelight --config /Users/aayushbajaj/.config/yabai/limelight/limelightrc &>/dev/null &


# adjusting window borders

yabai -m config layout bsp
yabai -m config top_padding 15
yabai -m config bottom_padding 15
yabai -m config left_padding 15
yabai -m config right_padding 15
yabai -m config window_gap 15

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap



echo "yabai configuration loaded.."
